apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:masters
      rolearn: arn:aws:iam::211125745138:role/terraform-eks-node
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::211125745138:user/vpc_emma
      username: vpc_emma
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-06-21T01:36:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "890"